# Step 1

In [2]:
import numpy as np

# Step 2

In [7]:
i=np.empty(5,dtype=int)
f=np.empty(5,dtype=float)
c=np.empty(5,dtype=complex)
print("Integer Array (size - "+str(i.size)+") - ")
print(i)
print()
print("Float Array (size - "+str(i.size)+") - ")
print(f)
print()
print("Complex Array (size - "+str(i.size)+") - ")
print(c)

Integer Array (size - 5) - 
[          0           0 -2015381856         648           0]

Float Array (size - 5) - 
[0.e+000 5.e-324 0.e+000 0.e+000 0.e+000]

Complex Array (size - 5) - 
[1.37616100e-311+2.02566915e-322j 0.00000000e+000+0.00000000e+000j
 4.45051270e-308+1.11420562e+092j 2.79437461e+276+1.27378631e+074j
 2.63044058e+180+2.57726435e-312j]


# Step 3

In [22]:
a=np.arange(9).reshape((3,3))
b=np.arange(9).reshape((3,3))

In [23]:
print(np.add(a,b))

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [24]:
print("Original Matrix - ")
print(a)
print()
print("Transposed Matrix - ")
print(a.T)

Original Matrix - 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Transposed Matrix - 
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [25]:
print("Matrix multiplication of a and b - ")
print(np.matmul(a,b))

Matrix multiplication of a and b - 
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [26]:
print("Element-wise multiplication of a and b - ")
print(a*b)

Element-wise multiplication of a and b - 
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [27]:
for i in range(a.shape[0]):
    print("Row"+str(i+1)+"- ",a[i])

Row1-  [0 1 2]
Row2-  [3 4 5]
Row3-  [6 7 8]


In [47]:
for i in range(a.shape[1]):
    print("Column"+str(i+1)+"- ",a[:,i])

Column1-  [0 3 6]
Column2-  [1 4 7]
Column3-  [2 5 8]


In [48]:
print(a[0][0])

0


# Step 4

In [29]:
print(a[0:2])

[[0 1 2]
 [3 4 5]]


In [31]:
print(a[::-1])

[[6 7 8]
 [3 4 5]
 [0 1 2]]


# Step 5

In [46]:
import pandas as pd
df=pd.read_csv("datasets_794109_1364871_gross-enrollment-ratio-2013-2016.csv")
df=df.drop("State_UT",axis=1)
c=df.values
print(c)

[['2013-14' 95.88 91.97 ... '105.4' '96.61' '101.28']
 ['2013-14' 96.62 96.87 ... '59.83' '60.83' '60.3']
 ['2013-14' 129.12 127.77 ... '65.16' '65.38' '65.27']
 ...
 ['2014-15' 100.11 101.02 ... '79.82' '80.95' '80.36']
 ['2014-15' 101.78 102.91 ... '48.27' '51.82' '49.95']
 ['2014-15' 98.85 101.43 ... '54.57' '53.81' '54.21']]
